# -*- coding: utf-8 -*-
"""metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QUBm4VeNFBl-IJ5Fm-qL8v6OdBUKeIl
"""

import torch

def multi_label_accuracy(y_pred, y_true, threshold=0.5):
    """
    Compute multi-label accuracy with a given threshold.

    Args:
        y_pred (Tensor): Raw model outputs (logits).
        y_true (Tensor): Ground truth binary labels.
        threshold (float): Threshold to decide positive class.

    Returns:
        float: Accuracy score.
    """
    y_pred_tag = (torch.sigmoid(y_pred) > threshold).float()
    correct_results_sum = (y_pred_tag == y_true).sum().float()
    acc = correct_results_sum / torch.numel(y_true)
    return acc.item()