# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cwNOy7yfmYh7I110qvc-kAXusMbpXor
"""

import torch
from transformers import AutoTokenizer
from kobert_model import HateSpeechClassifier

def predict(texts, model_path, device, max_length=128):
    tokenizer = AutoTokenizer.from_pretrained("skt/kobert-base-v1")
    model = HateSpeechClassifier()
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.to(device)
    model.eval()

    encodings = tokenizer(
        texts,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors='pt'
    )

    input_ids = encodings['input_ids'].to(device)
    attention_mask = encodings['attention_mask'].to(device)

    with torch.no_grad():
        outputs = model(input_ids, attention_mask)
        preds = torch.argmax(outputs, dim=1)

    return preds.cpu().tolist()